package ar.edu.unlam.pb1.interfaz.enums;

public enum MenuPrincipal {
	AGREGAR_LATA_PINTURA, 
	VENDER_LATAS_PINTURA, 
	MOSTRAR_CANTIDAD_LATAS_EN_STOCK_POR_TIPO,
	MOSTRAR_LATAS_PINTURA_MAS_BARATA_POR_TIPO,
	MOSTRAR_RESUMEN_PINTURERIA, 
	SALIR
}
